"$schema" = 'https://starship.rs/config-schema.json'

#format = """
#[╭─user───❯](bold blue) $username $hostname
#[┣─project❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[╰─cmd────❯](bold green) 
#"""

#format = """
#(bold blue) $username $hostname (underline)
#[project ❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[cmd     ❯](bold green) 
#"""

#format = """
#(bold blue) $username $hostname
#──────────────
#[╭─project❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[╰─cmd────❯](bold green) 
#"""

format = """
(bold blue) $username $hostname
──────────────
[╭─dir❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
[╰─cmd❯](bold green) 
"""

#format = '$all'

[directory]
style = "bold red"

[username]
format = "[$user]($style) @"
style_user = "bold blue underline"
show_always = true

[hostname]
ssh_only = false
disabled = false
format = "[$hostname]($style) "
style = "bold yellow underline"


[git_branch]
format = "[$symbol$branch]($style) " # Controls how the branch name is displayed
style = "#ff6f00"  # Change 'green' to any other color